import:
  # - /home/zdz/.zdz/alacritty/.themes/default.yml
  - /home/zdz/.zdz/alacritty/.themes/dracula.yml
# 默认窗口无标题栏，16:9的窗口比例启动
window:
    startup_mode: Fullscreen
    # decorations: "none"
    # decorations: "full"
    # dimensions:
    #   columns: 120
    #   lines: 40

position:
    x: 0
    y: 100

padding:
    x: 5
    y: 5

# 背景半透明
background_opacity: 0.94

mouse:
  hide_when_typing: true

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  # shift key and doubleclick left key to clipboard.
  save_to_clipboard: true

# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
font:
  # size: 10
  size: 8.5

  # normal:
     # family: Sauce Code Pro Light Nerd Font Complete Mono
     # family: Sauce Code Pro Light Nerd Font Complete Mono
     # style: Regular

  # bold:
     # family: Sauce Code Pro Bold Nerd Font Complete Mono
     # style: Bold

  # italic:
     # family: Sauce Code Pro Italic Nerd Font Complete Mono
     # style: Italic



# 外壳
# shell:
  # program: /usr/bin/zsh
  # args:
    # - "/usr/bin/tmux new -A -s main"



shell:
  # program: /bin/bash
  program: /usr/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"


key_bindings:
    # - { key: Space,  mods:  Super,  mode: ~Search,    action: ToggleSimpleFullscreen}
  - { key: V,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode        }
  - { key: F11,       mode: ~Search,                action: ToggleFullscreen      }
  - { key: V,         mods: Control,                action: Paste                 }
  - { key: C,         mods: Control,                action: Copy                  }
  - { key: C,         mods: Control|Shift,          chars: "\x03"                 }  
  - { key: Q,         mods: Control|Shift|Alt,      action: "Quit"                }
  - { key: PageUp,    mods: Shift,                  action: ScrollPageUp          }
  - { key: PageDown,  mods: Shift,                  action: ScrollPageDown        }
