#!/bin/bash
PATH_HOME="$HOME"
PATH_CUR="$(pwd)"

## nvim
PATH_NVIM="$PATH_HOME/.config/nvim"
PATH_NVIM_INIT_LN="$PATH_NVIM/init.vim"
PATH_NVIM_INIT="$PATH_CUR/nvim/init.vim"
ln -sf $PATH_NVIM_INIT $PATH_NVIM_INIT_LN



## terminator
PATH_TERMINATOR="$PATH_HOME/.config/terminator"
PATH_TERMINATOR_CONFIG_LN="$PATH_TERMINATOR/config"
PATH_TERMINATOR_CONFIG="$PATH_CUR/terminator/config"
ln -sf $PATH_TERMINATOR_CONFIG $PATH_TERMINATOR_CONFIG_LN
