#!/bin/bash
PATH_HOME="$HOME"
PATH_CUR="$(pwd)"

## nvim
PATH_NVIM="$PATH_HOME/.config/nvim"
PATH_NVIM_INIT_LN="$PATH_NVIM/init.vim"
PATH_NVIM_INIT="$PATH_CUR/nvim/init.vim"
ln -sf $PATH_NVIM_INIT $PATH_NVIM_INIT_LN



## terminator
PATH_TERMINATOR="$PATH_HOME/.config/terminator"
PATH_TERMINATOR_CONFIG_LN="$PATH_TERMINATOR/config"
PATH_TERMINATOR_CONFIG="$PATH_CUR/terminator/config"
ln -sf $PATH_TERMINATOR_CONFIG $PATH_TERMINATOR_CONFIG_LN



## gtk-3.0
PATH_GTK3="$PATH_HOME/.config/gtk-3.0"
PATH_GTK3_LN="$PATH_GTK3"
PATH_GTK3="$PATH_CUR/gtk-3.0"
ln -sf $PATH_GTK3 $PATH_GTK3_LN





